### ISSUE TITLE
Can laneaf detect the horizontal lane?

### ISSUE THREAD

**Issue by guoguangchao** [sel118/LaneAF#10]
Thanks for your great work! LaneAF clustering lane pixels  row-by-row, from bottom to top. Can LaneAF detect the vertical lane and horizontal lane at the same time? like the picture below,thanks

![微信截图_20210429135239](https://user-images.githubusercontent.com/5878481/116507629-32a29580-a8f2-11eb-9ed5-56f2d078a2f4.png)

**Comment by arangesh** [comment]
It should be possible to do this by creating a separate set of outputs (i.e. binary mask, HAF and VAF) for horizontal lines. You also would have to adapt the `generateAFs()` and `decodeAFs()` functions in `utils/affinity_fields.py` so that both these procedures operate from left to right (or right to left) instead of bottom to top.

**Comment by guoguangchao** [comment]
> 
> 
> It should be possible to do this by creating a separate set of outputs (i.e. binary mask, HAF and VAF) for horizontal lines. You also would have to adapt the `generateAFs()` and `decodeAFs()` functions in `utils/affinity_fields.py` so that both these procedures operate from left to right (or right to left) instead of bottom to top.

thanks for your answer,Do you mean like this?
![horizontal_vertical_lane](https://user-images.githubusercontent.com/5878481/116659643-7b2a8380-a9c4-11eb-8633-6db07acf0479.png)

**Comment by arangesh** [comment]
Yes, your understanding is correct. In addition to the separate heads for horizontal and vertical lines, you would also have separate `generateAFs()` and `decodeAFs()` functions for horizontal and vertical lines respectively. You can modify the existing functions in `utils/affinity_fields` to create these functions for horizontal lines.

**Comment by guoguangchao** [comment]
Thanks for your answer. It's very helpful

**Comment by wywywy01** [comment]
Did you experiment with the results of horizontal lane lines？
and how about laneatt model on horizontal lane lines？
