### ISSUE TITLE
parameter 'down_ratio' ablation study

### ISSUE THREAD

**Issue by Jiayi719** [sel118/LaneAF#17]
Hello, have you ever tried different values of parameter 'down_ratio'? I find one line code of its acceptable values in class DLASeg.
`assert down_ratio in [2, 4, 8, 16]`
So can you tell me the performance contrast of this parameter? Thank you very much.

**Comment by arangesh** [comment]
You can find some ablation experiments on this in the paper. On TuSimple, `down_ratio=4` works best,

**Comment by Jiayi719** [comment]
Yes, I see it. As I know there are some annotation errors in TuSimple dataset. So have you conducted the same ablation experiments on CULane?
