### ISSUE TITLE
About ignore_label

### ISSUE THREAD

**Issue by Jiayi719** [sel118/LaneAF#18]
Why the seg label would contain 255 in Tusimple and CULane?

**Comment by Jiayi719** [comment]
I got it. The GroupRandomRotation will pad board value 255 in the seg label
`                tf.GroupRandomRotation(degree=(-1, 1), interpolation=(cv2.INTER_LINEAR, cv2.INTER_NEAREST), padding=(self.mean, (self.ignore_label, ))),
`

**Comment by arangesh** [comment]
We pad the image with 255 so that these pixels can be ignored during loss calculation. This is because we do not know the true class of these border pixels after random rotations. If we use zero values, that would mean that the border pixels are all background - which is not necessarily the case.

**Comment by Jiayi719** [comment]
Yes, your are right. How much does random rotations affect the performance?

**Comment by arangesh** [comment]
You can check our paper for ablation experiments on TuSimple. In our experience, random transformations do lead to some marginal improvements and produce better affinity fields.

**Comment by Jiayi719** [comment]
I see it. It does lead a marginal improvement. Thanks for your reply.
