### ISSUE TITLE
Evaluation error (Implementation-wise)

### ISSUE THREAD

**Issue by Ebraheem1** [sel118/LaneAF#27]
In Line 107 in train_culane.py `train_acc = accuracy_score((pred > 0.5).astype(np.int64), (target > 0.5).astype(np.int64))`

Shouldn't it be the other way around `train_acc = accuracy_score((target > 0.5).astype(np.int64), (pred > 0.5).astype(np.int64))`?
According to sklearn, the ground truth labels should be the first parameter.

**Comment by arangesh** [comment]
Thanks for pointing this out. I have pushed a fix for this.
