### ISSUE TITLE
good job for lane detection

### ISSUE THREAD

**Issue by canteen-man** [sel118/LaneAF#30]
I think this is a good job for lane cluster.
Because the cluster method in lanenet isn't direct
By using the lanenet,when some points can't merge the same cluster or same lane,I can't explain why.
And the dbscan is not quickly enough on the embedded device.

But,if separate one lane in two parts,and between these two parts has a space,the VAF could handle this situation?  

And why there are no ablation study for compare the lanenet cluster branch and this cluster method.
Becasue I think this paper main idea is the cluster,not promoting the mainiou for the sementic segmentation.

**Comment by arangesh** [comment]
- Yes, you are correct that our primary contribution is the proposed clustering approach.
- Yes, the VAF could potentially recover complete lanes even if the binary mask has some "gap" in between parts as long as the direction of the lane does not change drastically.
- Comparing our clustering with the visual clustering proposed in LaneNet would indeed be interesting and useful. However, we do all our primary comparisons on CULane. I could not find an official LaneNet implementation for that, and we did not have the time to do this before the deadline. This may be something I look into later.
