### ISSUE TITLE
Question about equation 6 in the paper？

### ISSUE THREAD

**Issue by wywywy01** [sel118/LaneAF#32]
Thanks for your code and paper.

When I read your paper , I have some trouble in 'Decoding HAFS and VAFS'. 

In equation (6),  the index 'i' range is (0, | C_k | - 1)， which means every pixel of C_k cluster in y-1 row,  but 'i' is as the pixel index of L lane in y row,  and the range is right?

![image](https://user-images.githubusercontent.com/22450352/129861721-2e7d824a-2a1a-4c02-a300-03f964629042.png)

**Comment by arangesh** [comment]
I think you're right. The range of summation should be over all pixels belonging to lane `l` in row `y`. Accordingly, the normalization term should also be changed from `|C^k|`. Thanks for pointing this out. I will make changes to the arXiv version.
