### ISSUE TITLE
Does the block of DLA32 use basicblock?

### ISSUE THREAD

**Issue by cc19860606** [sel118/LaneAF#35]
I train the model on culane dataset, but Fmeasure is 77.1624, which is under 77.41 you reported. Does the block of DLA32 is basicblock? or Bottleneck, BottleneckX in the pose_dla_dcn.py.

**Comment by arangesh** [comment]
You can achieve the score reported in the paper using our pre-trained model weights. You might see some variability in scores when you train your own model.

As for DLA34, we make use of BasicBlocks as seen [here](https://github.com/sel118/LaneAF/blob/8cf6dd62f0e52bda3e9b1e221ab0b371d31b6c9d/models/dla/pose_dla_dcn.py#L312).
