### ISSUE TITLE
bias=-2.19

### ISSUE THREAD

**Issue by mishakin** [sel118/LaneAF#38]
Hey @arangesh,
Thanks for the great method and the implementation. The results look very good.
I was going through your code and came across a manually set bias [here](https://github.com/sel118/LaneAF/blob/e10ca89b485681f8412bfd120c2675ae2b13c990/models/erfnet/erfnet.py#L163). I wonder where this constant came from and what it means.

Thanks in advance,
Sergey,

**Comment by aoluming** [comment]
> Hey @arangesh, Thanks for the great method and the implementation. The results look very good. I was going through your code and came across a manually set bias [here](https://github.com/sel118/LaneAF/blob/e10ca89b485681f8412bfd120c2675ae2b13c990/models/erfnet/erfnet.py#L163). I wonder where this constant came from and what it means.
> 
> Thanks in advance, Sergey,

This bias comes from the paper'Focal Loss for Dense Object Detection' .You can see the illustration in chapter 4.1 Initialization.
The bias is used for the imbalance for the positive and negative samples at the beginning of training. Hope this would help you.

**Comment by mishakin** [comment]
Thanks a lot, @aoluming , it was helpful.
