### ISSUE TITLE
how to test on images?

### ISSUE THREAD

**Issue by lucky-xu-1994** [sel118/LaneAF#5]
hi! thanks for your great work! I'm troubled with how to test on images.
here are my codes for testing on images.
![image](https://user-images.githubusercontent.com/57120921/112929039-479cd500-914a-11eb-91d3-712deb295afe.png)
and I have tried like this.
![image](https://user-images.githubusercontent.com/57120921/112929099-5e432c00-914a-11eb-86bc-ff20558a47ec.png)
first it will download .pth
![image](https://user-images.githubusercontent.com/57120921/112929225-9185bb00-914a-11eb-98fc-94b05035563d.png)
and then return error:
![image](https://user-images.githubusercontent.com/57120921/112929300-b7ab5b00-914a-11eb-9382-ca9d450106d8.png)
so,how can I solve this problem? please help! thanks.

**Comment by arangesh** [comment]
You forgot to include the batch dimension in the input image. Your input image size needs to be `(1, 3, 288, 832)` instead of `(3, 288, 832)` that you currently have.

**Comment by lucky-xu-1994** [comment]
> You forgot to include the batch dimension in the input image. Your input image size needs to be `(1, 3, 288, 832)` instead of `(3, 288, 832)` that you currently have.

yes, you are right! thanks!

**Comment by fjremnav** [comment]
@lucky-xu-1994 

  Do you mind sharing your code?

Thanks,

**Comment by lucky-xu-1994** [comment]
> @lucky-xu-1994
> 
> Do you mind sharing your code?
> 
> Thanks,
you can try as I put in the first picture by adding one line of code.
![image](https://user-images.githubusercontent.com/57120921/114116917-242b1480-9918-11eb-9278-96e4493c1eb2.png)

**Comment by lucky-xu-1994** [comment]
@fjremnav 
you can try as I put in the first picture just by adding a line of code like this:
![image](https://user-images.githubusercontent.com/57120921/114117139-9c91d580-9918-11eb-8a33-22484bf4b1b1.png)

**Comment by fjremnav** [comment]
Below is my code:

        img=cv2.imread(args.input_img).astype(np.float32)/255.
        img=cv2.resize(img[14:,:,:], (1664, 576), interpolation=cv2.INTER_LINEAR)
        img=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_transforms = transforms.Compose([
                tf.GroupRandomScale(size=(0.5, 0.5), interpolation=(cv2.INTER_LINEAR, cv2.INTER_NEAREST)),
                tf.GroupNormalize(mean=([0.485, 0.456, 0.406], (0, )), std=([0.229, 0.224, 0.225], (1, ))),
            ])
        input_img,_ = img_transforms((img,img))
        input_img = torch.from_numpy(input_img).permute(2,0,1).contiguous().float()
        input_img = np.expand_dims(input_img, axis=0).astype(np.float32)
        if args.cuda:
            input_img = Variable(torch.tensor(input_img).cuda())

        st_time = datetime.now()
        # do the forward pass
        outputs = net(input_img)[-1]

When I run:

 python ./infer_images.py --input_img ./test00300.png  --snapshot tusimple-weights/net_0012.pth

I got the memory access error beow:

  File "/home/test/2TB/LaneAF/models/dla/DCNv2/dcn_v2.py", line 159, in forward
    offset = torch.cat((o1, o2), dim=1)
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/THC/THCCachingHostAllocator.cpp:278
Segmentation fault (core dumped)

It will be helpful if you can share your code.

Thanks,

**Comment by lucky-xu-1994** [comment]
> Below is my code:
> 
> ```
>     img=cv2.imread(args.input_img).astype(np.float32)/255.
>     img=cv2.resize(img[14:,:,:], (1664, 576), interpolation=cv2.INTER_LINEAR)
>     img=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
>     img_transforms = transforms.Compose([
>             tf.GroupRandomScale(size=(0.5, 0.5), interpolation=(cv2.INTER_LINEAR, cv2.INTER_NEAREST)),
>             tf.GroupNormalize(mean=([0.485, 0.456, 0.406], (0, )), std=([0.229, 0.224, 0.225], (1, ))),
>         ])
>     input_img,_ = img_transforms((img,img))
>     input_img = torch.from_numpy(input_img).permute(2,0,1).contiguous().float()
>     input_img = np.expand_dims(input_img, axis=0).astype(np.float32)
>     if args.cuda:
>         input_img = Variable(torch.tensor(input_img).cuda())
> 
>     st_time = datetime.now()
>     # do the forward pass
>     outputs = net(input_img)[-1]
> ```
> 
> When I run:
> 
> python ./infer_images.py --input_img ./test00300.png --snapshot tusimple-weights/net_0012.pth
> 
> I got the memory access error beow:
> 
> File "/home/test/2TB/LaneAF/models/dla/DCNv2/dcn_v2.py", line 159, in forward
> offset = torch.cat((o1, o2), dim=1)
> RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/THC/THCCachingHostAllocator.cpp:278
> Segmentation fault (core dumped)
> 
> It will be helpful if you can share your code.
> 
> Thanks,

maybe you need to assign a specific gpu to run this if you have muti-gpu.
try this:
CUDA_VISIBLE_DEVICES=0 python ./infer_images.py --input_img ./test00300.png --snapshot tusimple-weights/net_0012.pth

**Comment by fjremnav** [comment]
I have only one GPU

Thanks,

**Comment by st311325** [comment]
检测图片的完整代码可以分享一下吗 ，谢谢@lucky-xu-1994
